config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  concern :voted do
    member do
      patch :like
      patch :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch 'best', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :award, dependent: :destroy
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  validates :title, :body, presence: true
  after_create :create_subscription

  def other_answers
    answers.where.not(id: best_answer_id)
  end

  def create_subscription
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i[show destroy update]
  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionFullSerializer
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :accepted
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy

    @question.destroy
    render json: { messages: ['Your question deleted'] }
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

   def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit destroy update]
  before_action :find_subsription, only: [:show]

  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
    gon.push({ question_id: @question.id })
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.build_award
  end

  def edit; end

  def create
    @question = current_user.questions.create(question_params)
    @question.author = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def destroy
    @question.destroy if current_user.author?(@question)
    redirect_to questions_path
  end

  def update
    @question.update(question_params)
  end

  private

  def find_subsription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[name url _destroy id],
                                                    award_attributes: %i[name image])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question_channel',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_all_answers.html.slim
-if !@question.best_answer.nil?
  .best-answer
    = render 'answers/best_answer', resource: @question.best_answer
    
.other-answers
  = render @question.other_answers

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question
.question-errors

= form_with model: @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p  
    = f.label :body
    = f.text_area :body
  p  
    = f.label :files
    = f.file_field :files, multiple: true

    p Links:
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

    p Award:
    = f.fields_for :award do |a|
      p
        = a.label :name, 'Award title'
        = a.text_field :name
      p
        = a.label :image
        = a.file_field :image

  p = f.submit 'Ask a question'

app/views/questions/_question.html.slim
p = question.title
p = question.body
p = render 'shared/vote', resource: question

.question id="question-#{question.id}"
  .question-errors
    = render 'shared/errors', resource: @question

  - if @question.files.attached?
    .attachments
      - @question.files.each do |file|
        p id="attachment_#{file.id}"
          = link_to file.filename.to_s, url_for(file)
          br
          - if can? :destroy, file
            = link_to 'Delete the file', attachment_path(file.id), method: :delete, remote: true

  .links
  p Links:
  - @question.links.each do |link|
    div id="link_#{link.id}"
      = link_to link.name, link.url
      - if link.is_a_gist?
        = javascript_include_tag link.url + '.js'

      - if can? :destroy, link
        p = link_to 'Delete link', link_path(link.id), method: :delete, remote: true

  .award
  p Award:
  ul
    - if @question.award
      = @question.award.name
      = image_tag(@question.award.image, size: "50x50")


  - if can? :destroy, @question
    p= link_to 'Delete the question', question_path(@question), method: :delete
  - if can? :update, @question
    p= link_to 'Edit the question', '#', class: 'edit-question-link', data: { question_id: question.id }

    = form_with model: @question, class: 'hidden', local: false, html: { id: "edit-question-#{question.id}" } do |f|
      p
        = f.label :title
        = f.text_field :title
      p
        = f.label :body, 'Your question'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        
        p Links:
        = f.fields_for :links do |l|
          = render 'shared/link_fields', f: l
        .links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      p    
      
      = f.submit 'Save'

  .subscription      
    = render 'subscriptions/subscription', resource: question

  .question_comments
    p Comments
    = render question.comments
  - if can? :create, Comment
    = render 'comments/form_question', resource: question

app/views/questions/_question_channel.html.slim
.questions
  p= question.title
  p= question.body

app/views/questions/index.html.slim
- if can?(:create, Question)
p= link_to 'Ask a question', new_question_path
.questions
    - @questions.each do |question|
        p= question.title
        p= question.body 

app/views/questions/new.html.slim
h2 Create a question

= render 'form'

app/views/questions/show.html.slim
h2 Question
= render @question

h3 Answers
.answers
  = render 'all_answers'

- if can? :create, Answer  
  = render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>