config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  concern :voted do
    member do
      patch :like
      patch :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch 'best', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
    can :all, User

  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :read, :all
    can [:create, :make_comment], [Question, Answer, Comment, Subscription]
    can [:update, :destroy], [Question, Answer, Subscription], user_id: user.id
    can [:like, :dislike, :cancel], [Question, Answer] do |votable|
      votable.user_id != user.id
    end
    can :destroy, Link, linkable: { user_id: user.id }
    can :mark_as_best, Answer, question: {user_id: user.id}
    can :me, User, user_id: user.id
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  def mark_as_best
    question.update(best_answer_id: id)
    question.award&.update!(user: author)
  end

  after_create :send_notification

  private

  def send_notification
    NotificationsJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true
  validates :name, presence: true

  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true
  validates :name, :url, presence: true

  validates :url, format: {
    with: URI::DEFAULT_PARSER.make_regexp(%w[http https]),
    message: 'is not a valid URL'
  }

  def is_a_gist?
    url.start_with?('https://gist.github.com')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :award, dependent: :destroy
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  validates :title, :body, presence: true
  after_create :create_subscription

  def other_answers
    answers.where.not(id: best_answer_id)
  end

  def create_subscription
    subscriptions.create(user: author)
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[github vkontakte]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :awards
  has_many :votes, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def author?(smth)
    id == smth.user_id
  end

  def self.find_for_oauth(auth)
    Services::FindForOauth.new(auth).call
  end

  def create_autorization(auth)
    authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  def subscribed?(question)
    subscriptions.where(question: question).exists?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :value, presence: true
  validates :user, presence: true, uniqueness: { scope: %i[votable_id votable_type] }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  after_action :publish_answer, only: [:create]
  authorize_resource

  def create
    @answer = question.answers.create(answer_params.merge(author: current_user))

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json do
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    answer.update(answer_params) if current_user.author?(answer)
    @question = answer.question
  end

  def destroy
    if current_user.author?(answer)
      answer.destroy
      redirect_to question_path(answer.question), notice: 'Your answer successfully deleted.'
    else
      redirect_to question_path(answer.question)
    end
  end

  def best
    @question = answer.question
    answer.mark_as_best if current_user.author?(answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url _destroy])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : question.answers.new
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answers/#{params[:question_id]}",
      ApplicationController.render(
        partial: 'answers/answer_channel',
        locals: { answer: @answer }
      )
    )
  end

  helper_method :question, :answer
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @awards = current_user.awards
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  authorize_resource

  def destroy
    @link = Link.find(params[:id])
    @link.destroy if current_user.author?(@link.linkable)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def search
    service = SearchService.new(search_params)
    @result = service.call
    #debugger
  end

  private

  def search_params
    params.permit(:body, :type)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= include_gon %>
    <%= Gon::Base.render_data %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/nav' %>

    <% unless notice.nil? %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>


    <% unless alert.nil? %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>

    <%= yield %>


  </body>
</html>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_link_fields.html.slim
.nested-fields
  .name
    = f.label :name, 'Link name'
    = f.text_field :name
  .url
    = f.label :url
    = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_nav.html.slim
span
  - if user_signed_in?
    = current_user.email
    br
    = link_to 'My Awards', awards_path
    br
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign in', :new_user_session
    br
    = link_to 'Registration', :new_user_registration

.search
  = form_with url: search_path, local: true, method: :get do |f|
    .d-flex
      = f.text_field :body, class: 'mr-sm-2 form-control'
      = f.select :type, SearchService::TYPES, class: 'form-control'
      = f.submit 'Search', class: 'btn btn-outline-success mx-3'

app/views/shared/_vote.html.slim
.vote

  - if current_user && !current_user.author?(resource)

    = link_to 'Like', polymorphic_path(resource, action: :like), method: :patch, data: { type: :json}, remote: true
    br

    = link_to 'Dislike', polymorphic_path(resource, action: :dislike), method: :patch, data: { type: :json }, remote: true
    br

    = link_to 'Cancel the vote', polymorphic_path(resource, action: :cancel), method: :delete, data: { type: :json }, remote: true

    .rating id= "rating-#{resource.class.name.downcase}-#{resource.id}"
     = resource.rating        