config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  get 'search', action: :search, controller: 'search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  concern :voted do
    member do
      patch :like
      patch :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch 'best', on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, dependent: :destroy, as: :votable
  has_many :comments, dependent: :destroy, as: :commentable

  has_many_attached :files
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  def mark_as_best
    question.update(best_answer_id: id)
    question.award&.update!(user: author)
  end

  after_create :send_notification

  private

  def send_notification
    NotificationsJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  after_action :publish_answer, only: [:create]
  authorize_resource

  def create
    @answer = question.answers.create(answer_params.merge(author: current_user))

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json do
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    answer.update(answer_params) if current_user.author?(answer)
    @question = answer.question
  end

  def destroy
    if current_user.author?(answer)
      answer.destroy
      redirect_to question_path(answer.question), notice: 'Your answer successfully deleted.'
    else
      redirect_to question_path(answer.question)
    end
  end

  def best
    @question = answer.question
    answer.mark_as_best if current_user.author?(answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url _destroy])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : question.answers.new
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answers/#{params[:question_id]}",
      ApplicationController.render(
        partial: 'answers/answer_channel',
        locals: { answer: @answer }
      )
    )
  end

  helper_method :question, :answer
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:create ]
  before_action :find_answer, only: %i[ show update destroy ]

  authorize_resource

  def show
    render json: @answer, serializer: AnswerFullSerializer
  end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.author = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update

    if @answer.update(answer_params)
      render json: @answer, status: :accepted
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    render json: { messages: ['Your answer deleted'] }
  end


  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer id="answer-#{answer.id}"
  p= answer.author.email

  p= answer.body

  p= render 'shared/vote', resource: answer

.links
  p Links:
  ul
    -answer.links.each do |link|
     div id="link_#{link.id}"
      li= link_to link.name, link.url
      - if link.is_a_gist?
        = javascript_include_tag link.url + '.js'
      - if can? :destroy, link
      p = link_to 'Delete link', link_path(link.id), method: :delete, remote: true

  - if answer.files.attached?
    .attachments
    - answer.files.each do |file|
      p id="attachment_#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        br
        - if can? :destroy, file
          = link_to 'Delete the file', attachment_path(file.id), method: :delete, remote: true

  - if can? :update, answer
    = link_to 'Choose', best_answer_path(answer), remote: true, method: :patch

  - if can? :destroy, answer
    p= link_to 'Delete the answer', answer_path(answer), method: :delete
  - if can? :update, answer
    p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    p  
    	= f.label :body, 'Your answer'
    	= f.text_area :body
    p  
      = f.label :files
      = f.file_field :files, multiple: true

      p Links:
      = f.fields_for :links do |l|
        = render 'shared/link_fields', f: l
      .links
        = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
    p    
  	= f.submit 'Save'

.answer_comments
  p Comments:
  = render answer.comments
- if can? :create, Comment
  = render 'comments/form_answer', answer: answer    

app/views/answers/_answer_channel.html.slim
.answer id="answer-#{answer.id}"
  p= answer.author.email
  p= answer.body

app/views/answers/_best_answer.html.slim
.answer id="answer-#{@question.best_answer.id}"
  div
    = 'The best answer: '
  div
    = 'Author: '
    = @question.best_answer.author.email
  div
    = @question.best_answer.body

app/views/answers/_form.html.slim
= render 'shared/errors', resource: @answer
.answer-errors

= form_with model: [@question, @answer], class: 'new-answer', data: { type: :json } do |f|
  p
    = f.label :body
    = f.text_area :body
  p  
    = f.label :files
    = f.file_field :files, multiple: true

    p Links:
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      
  p = f.submit 'Leave an answer'

app/views/answers/best.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render 'questions/all_answers', resource: @question %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/delete.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if !answer.errors.present? %>
  $('#answer-<%= @answer.id %>').remove()
<% end %>

app/views/answers/new.html.slim
h2 Create an answer

= render 'form'

app/views/answers/show.html.slim
h1= @question.title
h3= @question.body
h2= @answer.body

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>